name: hex_coordinate
description: Coordinate system for hexagonal grids.
version: 1.0.1
repository: https://github.com/nearocodes/hex_grid

environment:
  sdk: ^3.6.0

dependencies:
  meta: ^1.15.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
